version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
        - echo Entered the install phase...
        - apt-get update -y
        - apt-get install -y yarn
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - yarn install
  build:
    commands:
      - echo Entered the build phase...
      - yarn build

artifacts:
  base-directory: build
  discard-paths: no
  files:
    - '**/*'